/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RoasteriesRouteImport } from './routes/roasteries'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminContentLinksRouteImport } from './routes/admin.content-links'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BrewSlugRouteImport } from './routes/brew.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as HubOperationsRouteImport } from './routes/hub.operations'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OriginsSlugRouteImport } from './routes/origins.$slug'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as PanelGrindingRouteImport } from './routes/panel.grinding'
import { Route as PanelManageRouteImport } from './routes/panel.manage'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as RoasteriesIndexRouteImport } from './routes/roasteries.index'
import { Route as RoasteriesSlugRouteImport } from './routes/roasteries.$slug'
import { Route as SitemapsContentDotxmlRouteImport } from './routes/sitemaps.content[.]xml'
import { Route as SitemapsProductsDotxmlRouteImport } from './routes/sitemaps.products[.]xml'
import { Route as SitemapsRoasteriesDotxmlRouteImport } from './routes/sitemaps.roasteries[.]xml'
import { Route as SitemapsStaticDotxmlRouteImport } from './routes/sitemaps.static[.]xml'
import { Route as TastesSlugRouteImport } from './routes/tastes.$slug'
import { Route as AdminContentEditEntryIdRouteImport } from './routes/admin.content-edit.$entryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RoasteriesRoute = RoasteriesRouteImport.update({
  id: '/roasteries',
  path: '/roasteries',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentLinksRoute = AdminContentLinksRouteImport.update({
  id: '/admin/content-links',
  path: '/admin/content-links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/admin/operations',
  path: '/admin/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BrewSlugRoute = BrewSlugRouteImport.update({
  id: '/brew/$slug',
  path: '/brew/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HubOperationsRoute = HubOperationsRouteImport.update({
  id: '/hub/operations',
  path: '/hub/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const OriginsSlugRoute = OriginsSlugRouteImport.update({
  id: '/origins/$slug',
  path: '/origins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelGrindingRoute = PanelGrindingRouteImport.update({
  id: '/grinding',
  path: '/grinding',
  getParentRoute: () => PanelRoute,
} as any)
const PanelManageRoute = PanelManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => PanelRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const RoasteriesIndexRoute = RoasteriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoasteriesRoute,
} as any)
const RoasteriesSlugRoute = RoasteriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RoasteriesRoute,
} as any)
const SitemapsContentDotxmlRoute = SitemapsContentDotxmlRouteImport.update({
  id: '/sitemaps/content.xml',
  path: '/sitemaps/content.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsProductsDotxmlRoute = SitemapsProductsDotxmlRouteImport.update({
  id: '/sitemaps/products.xml',
  path: '/sitemaps/products.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsRoasteriesDotxmlRoute =
  SitemapsRoasteriesDotxmlRouteImport.update({
    id: '/sitemaps/roasteries.xml',
    path: '/sitemaps/roasteries.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapsStaticDotxmlRoute = SitemapsStaticDotxmlRouteImport.update({
  id: '/sitemaps/static.xml',
  path: '/sitemaps/static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TastesSlugRoute = TastesSlugRouteImport.update({
  id: '/tastes/$slug',
  path: '/tastes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentEditEntryIdRoute = AdminContentEditEntryIdRouteImport.update({
  id: '/admin/content-edit/$entryId',
  path: '/admin/content-edit/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/forbidden': typeof ForbiddenRoute
  '/orders': typeof OrdersRouteWithChildren
  '/panel': typeof PanelRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/roasteries': typeof RoasteriesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/content-links': typeof AdminContentLinksRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brew/$slug': typeof BrewSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/hub/operations': typeof HubOperationsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/origins/$slug': typeof OriginsSlugRoute
  '/panel/grinding': typeof PanelGrindingRoute
  '/panel/manage': typeof PanelManageRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/roasteries/$slug': typeof RoasteriesSlugRoute
  '/sitemaps/content.xml': typeof SitemapsContentDotxmlRoute
  '/sitemaps/products.xml': typeof SitemapsProductsDotxmlRoute
  '/sitemaps/roasteries.xml': typeof SitemapsRoasteriesDotxmlRoute
  '/sitemaps/static.xml': typeof SitemapsStaticDotxmlRoute
  '/tastes/$slug': typeof TastesSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/roasteries/': typeof RoasteriesIndexRoute
  '/admin/content-edit/$entryId': typeof AdminContentEditEntryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/forbidden': typeof ForbiddenRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/content-links': typeof AdminContentLinksRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brew/$slug': typeof BrewSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/hub/operations': typeof HubOperationsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/origins/$slug': typeof OriginsSlugRoute
  '/panel/grinding': typeof PanelGrindingRoute
  '/panel/manage': typeof PanelManageRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/roasteries/$slug': typeof RoasteriesSlugRoute
  '/sitemaps/content.xml': typeof SitemapsContentDotxmlRoute
  '/sitemaps/products.xml': typeof SitemapsProductsDotxmlRoute
  '/sitemaps/roasteries.xml': typeof SitemapsRoasteriesDotxmlRoute
  '/sitemaps/static.xml': typeof SitemapsStaticDotxmlRoute
  '/tastes/$slug': typeof TastesSlugRoute
  '/auth': typeof AuthIndexRoute
  '/blog': typeof BlogIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/panel': typeof PanelIndexRoute
  '/products': typeof ProductsIndexRoute
  '/roasteries': typeof RoasteriesIndexRoute
  '/admin/content-edit/$entryId': typeof AdminContentEditEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/forbidden': typeof ForbiddenRoute
  '/orders': typeof OrdersRouteWithChildren
  '/panel': typeof PanelRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/roasteries': typeof RoasteriesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/content-links': typeof AdminContentLinksRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brew/$slug': typeof BrewSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/hub/operations': typeof HubOperationsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/origins/$slug': typeof OriginsSlugRoute
  '/panel/grinding': typeof PanelGrindingRoute
  '/panel/manage': typeof PanelManageRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/roasteries/$slug': typeof RoasteriesSlugRoute
  '/sitemaps/content.xml': typeof SitemapsContentDotxmlRoute
  '/sitemaps/products.xml': typeof SitemapsProductsDotxmlRoute
  '/sitemaps/roasteries.xml': typeof SitemapsRoasteriesDotxmlRoute
  '/sitemaps/static.xml': typeof SitemapsStaticDotxmlRoute
  '/tastes/$slug': typeof TastesSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/roasteries/': typeof RoasteriesIndexRoute
  '/admin/content-edit/$entryId': typeof AdminContentEditEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/design-system'
    | '/forbidden'
    | '/orders'
    | '/panel'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/quiz'
    | '/roasteries'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/content'
    | '/admin/content-links'
    | '/admin/finance'
    | '/admin/operations'
    | '/auth/verify'
    | '/blog/$slug'
    | '/brew/$slug'
    | '/collections/$slug'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/hub/operations'
    | '/orders/$id'
    | '/origins/$slug'
    | '/panel/grinding'
    | '/panel/manage'
    | '/products/$slug'
    | '/roasteries/$slug'
    | '/sitemaps/content.xml'
    | '/sitemaps/products.xml'
    | '/sitemaps/roasteries.xml'
    | '/sitemaps/static.xml'
    | '/tastes/$slug'
    | '/auth/'
    | '/blog/'
    | '/orders/'
    | '/panel/'
    | '/products/'
    | '/roasteries/'
    | '/admin/content-edit/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/design-system'
    | '/forbidden'
    | '/privacy'
    | '/profile'
    | '/quiz'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/content'
    | '/admin/content-links'
    | '/admin/finance'
    | '/admin/operations'
    | '/auth/verify'
    | '/blog/$slug'
    | '/brew/$slug'
    | '/collections/$slug'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/hub/operations'
    | '/orders/$id'
    | '/origins/$slug'
    | '/panel/grinding'
    | '/panel/manage'
    | '/products/$slug'
    | '/roasteries/$slug'
    | '/sitemaps/content.xml'
    | '/sitemaps/products.xml'
    | '/sitemaps/roasteries.xml'
    | '/sitemaps/static.xml'
    | '/tastes/$slug'
    | '/auth'
    | '/blog'
    | '/orders'
    | '/panel'
    | '/products'
    | '/roasteries'
    | '/admin/content-edit/$entryId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/design-system'
    | '/forbidden'
    | '/orders'
    | '/panel'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/quiz'
    | '/roasteries'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/content'
    | '/admin/content-links'
    | '/admin/finance'
    | '/admin/operations'
    | '/auth/verify'
    | '/blog/$slug'
    | '/brew/$slug'
    | '/collections/$slug'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/hub/operations'
    | '/orders/$id'
    | '/origins/$slug'
    | '/panel/grinding'
    | '/panel/manage'
    | '/products/$slug'
    | '/roasteries/$slug'
    | '/sitemaps/content.xml'
    | '/sitemaps/products.xml'
    | '/sitemaps/roasteries.xml'
    | '/sitemaps/static.xml'
    | '/tastes/$slug'
    | '/auth/'
    | '/blog/'
    | '/orders/'
    | '/panel/'
    | '/products/'
    | '/roasteries/'
    | '/admin/content-edit/$entryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ForbiddenRoute: typeof ForbiddenRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PanelRoute: typeof PanelRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  RoasteriesRoute: typeof RoasteriesRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminContentLinksRoute: typeof AdminContentLinksRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  BrewSlugRoute: typeof BrewSlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CompareSlugRoute: typeof CompareSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  HubOperationsRoute: typeof HubOperationsRoute
  OriginsSlugRoute: typeof OriginsSlugRoute
  SitemapsContentDotxmlRoute: typeof SitemapsContentDotxmlRoute
  SitemapsProductsDotxmlRoute: typeof SitemapsProductsDotxmlRoute
  SitemapsRoasteriesDotxmlRoute: typeof SitemapsRoasteriesDotxmlRoute
  SitemapsStaticDotxmlRoute: typeof SitemapsStaticDotxmlRoute
  TastesSlugRoute: typeof TastesSlugRoute
  AdminContentEditEntryIdRoute: typeof AdminContentEditEntryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roasteries': {
      id: '/roasteries'
      path: '/roasteries'
      fullPath: '/roasteries'
      preLoaderRoute: typeof RoasteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content-links': {
      id: '/admin/content-links'
      path: '/admin/content-links'
      fullPath: '/admin/content-links'
      preLoaderRoute: typeof AdminContentLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/brew/$slug': {
      id: '/brew/$slug'
      path: '/brew/$slug'
      fullPath: '/brew/$slug'
      preLoaderRoute: typeof BrewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/operations': {
      id: '/hub/operations'
      path: '/hub/operations'
      fullPath: '/hub/operations'
      preLoaderRoute: typeof HubOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/origins/$slug': {
      id: '/origins/$slug'
      path: '/origins/$slug'
      fullPath: '/origins/$slug'
      preLoaderRoute: typeof OriginsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/grinding': {
      id: '/panel/grinding'
      path: '/grinding'
      fullPath: '/panel/grinding'
      preLoaderRoute: typeof PanelGrindingRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/manage': {
      id: '/panel/manage'
      path: '/manage'
      fullPath: '/panel/manage'
      preLoaderRoute: typeof PanelManageRouteImport
      parentRoute: typeof PanelRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/roasteries/': {
      id: '/roasteries/'
      path: '/'
      fullPath: '/roasteries/'
      preLoaderRoute: typeof RoasteriesIndexRouteImport
      parentRoute: typeof RoasteriesRoute
    }
    '/roasteries/$slug': {
      id: '/roasteries/$slug'
      path: '/$slug'
      fullPath: '/roasteries/$slug'
      preLoaderRoute: typeof RoasteriesSlugRouteImport
      parentRoute: typeof RoasteriesRoute
    }
    '/sitemaps/content.xml': {
      id: '/sitemaps/content.xml'
      path: '/sitemaps/content.xml'
      fullPath: '/sitemaps/content.xml'
      preLoaderRoute: typeof SitemapsContentDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/products.xml': {
      id: '/sitemaps/products.xml'
      path: '/sitemaps/products.xml'
      fullPath: '/sitemaps/products.xml'
      preLoaderRoute: typeof SitemapsProductsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/roasteries.xml': {
      id: '/sitemaps/roasteries.xml'
      path: '/sitemaps/roasteries.xml'
      fullPath: '/sitemaps/roasteries.xml'
      preLoaderRoute: typeof SitemapsRoasteriesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/static.xml': {
      id: '/sitemaps/static.xml'
      path: '/sitemaps/static.xml'
      fullPath: '/sitemaps/static.xml'
      preLoaderRoute: typeof SitemapsStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tastes/$slug': {
      id: '/tastes/$slug'
      path: '/tastes/$slug'
      fullPath: '/tastes/$slug'
      preLoaderRoute: typeof TastesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content-edit/$entryId': {
      id: '/admin/content-edit/$entryId'
      path: '/admin/content-edit/$entryId'
      fullPath: '/admin/content-edit/$entryId'
      preLoaderRoute: typeof AdminContentEditEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface PanelRouteChildren {
  PanelGrindingRoute: typeof PanelGrindingRoute
  PanelManageRoute: typeof PanelManageRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelGrindingRoute: PanelGrindingRoute,
  PanelManageRoute: PanelManageRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface RoasteriesRouteChildren {
  RoasteriesSlugRoute: typeof RoasteriesSlugRoute
  RoasteriesIndexRoute: typeof RoasteriesIndexRoute
}

const RoasteriesRouteChildren: RoasteriesRouteChildren = {
  RoasteriesSlugRoute: RoasteriesSlugRoute,
  RoasteriesIndexRoute: RoasteriesIndexRoute,
}

const RoasteriesRouteWithChildren = RoasteriesRoute._addFileChildren(
  RoasteriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DesignSystemRoute: DesignSystemRoute,
  ForbiddenRoute: ForbiddenRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PanelRoute: PanelRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  RoasteriesRoute: RoasteriesRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminContentLinksRoute: AdminContentLinksRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  BrewSlugRoute: BrewSlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CompareSlugRoute: CompareSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  HubOperationsRoute: HubOperationsRoute,
  OriginsSlugRoute: OriginsSlugRoute,
  SitemapsContentDotxmlRoute: SitemapsContentDotxmlRoute,
  SitemapsProductsDotxmlRoute: SitemapsProductsDotxmlRoute,
  SitemapsRoasteriesDotxmlRoute: SitemapsRoasteriesDotxmlRoute,
  SitemapsStaticDotxmlRoute: SitemapsStaticDotxmlRoute,
  TastesSlugRoute: TastesSlugRoute,
  AdminContentEditEntryIdRoute: AdminContentEditEntryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
